packages:
  - "apps/*"
  - "packages/*"

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - "esbuild"
  - "prisma"
  - "sharp"
  - "unrs-resolver"
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
