export const vietnamProvinces = [
  { code: "ha-noi", label: "Hà Nội", aliases: ["hà nội"] },
  { code: "cao-bang", label: "Cao Bằng", aliases: ["cao bằng"] },
  { code: "tuyen-quang", label: "Tuyên Quang", aliases: ["tuyên quang"] },
  { code: "dien-bien", label: "Điện Biên", aliases: ["điện biên"] },
  { code: "lai-chau", label: "Lai Châu", aliases: ["lai châu"] },
  { code: "son-la", label: "Sơn La", aliases: ["sơn la"] },
  { code: "lao-cai", label: "Lào Cai", aliases: ["lào cai"] },
  { code: "thai-nguyen", label: "Thái Nguyên", aliases: ["thái nguyên"] },
  { code: "lang-son", label: "Lạng Sơn", aliases: ["lạng sơn"] },
  { code: "quang-ninh", label: "Quảng Ninh", aliases: ["quảng ninh"] },
  { code: "bac-ninh", label: "Bắc Ninh", aliases: ["bắc ninh"] },
  { code: "phu-tho", label: "Phú Thọ", aliases: ["phú thọ"] },
  { code: "hai-phong", label: "Hải Phòng", aliases: ["hải phòng"] },
  { code: "hung-yen", label: "Hưng Yên", aliases: ["hưng yên"] },
  { code: "ninh-binh", label: "Ninh Bình", aliases: ["ninh bình"] },
  { code: "thanh-hoa", label: "Thanh Hóa", aliases: ["thanh hóa"] },
  { code: "nghe-an", label: "Nghệ An", aliases: ["nghệ an"] },
  { code: "ha-tinh", label: "Hà Tĩnh", aliases: ["hà tĩnh"] },
  { code: "quang-tri", label: "Quảng Trị", aliases: ["quảng trị"] },
  { code: "hue", label: "Huế", aliases: ["huế"] },
  { code: "da-nang", label: "Đà Nẵng", aliases: ["đà nẵng"] },
  { code: "quang-ngai", label: "Quảng Ngãi", aliases: ["quảng ngãi"] },
  { code: "gia-lai", label: "Gia Lai", aliases: ["gia lai"] },
  { code: "khanh-hoa", label: "Khánh Hòa", aliases: ["khánh hòa"] },
  { code: "dak-lak", label: "Đắk Lắk", aliases: ["đắk lắk"] },
  { code: "lam-dong", label: "Lâm Đồng", aliases: ["lâm đồng"] },
  { code: "dong-nai", label: "Đồng Nai", aliases: ["đồng nai"] },
  { code: "ho-chi-minh", label: "TP. Hồ Chí Minh", aliases: ["tp.hcm", "tp. hcm", "hồ chí minh"] },
  { code: "tay-ninh", label: "Tây Ninh", aliases: ["tây ninh"] },
  { code: "dong-thap", label: "Đồng Tháp", aliases: ["đồng tháp"] },
  { code: "vinh-long", label: "Vĩnh Long", aliases: ["vĩnh long"] },
  { code: "an-giang", label: "An Giang", aliases: ["an giang"] },
  { code: "can-tho", label: "Cần Thơ", aliases: ["cần thơ"] },
  { code: "ca-mau", label: "Cà Mau", aliases: ["cà mau"] },
] as const;
